from __future__ import annotations

from typing import Dict


class SparkConfigBuilder:
    """Produces runtime configuration consumed by the SparkJS rendering harness."""

    def __init__(
        self,
        scene_uri: str,
        music_uri: str,
        shots_schedule: Dict,
        render_settings: Dict,
        output_paths: Dict,
    ) -> None:
        self.scene_uri = scene_uri
        self.music_uri = music_uri
        self.schedule = shots_schedule
        self.render_settings = render_settings
        self.output_paths = output_paths

    def build(self) -> Dict:
        fps = int(self.render_settings.get("fps", 30))
        resolution = self.render_settings.get("resolution", {"width": 1280, "height": 720})
        duration = float(self.schedule.get("timeline_end", 0.0))
        beats = self.schedule.get("beat_times", [])
        frame_padding = 5
        shots = self.schedule.get("shots", [])
        frames_dir = str(self.output_paths["frames_dir"])
        video_out = str(self.output_paths["video_output"])
        config = {
            "scene": {
                "plyUrl": self._normalize_uri(self.scene_uri),
            },
            "audio": {
                "path": self._normalize_uri(self.music_uri),
                "beats": beats,
                "tempo": self.schedule.get("tempo"),
            },
            "timeline": {
                "duration": duration,
                "targetDuration": self.schedule.get("target_duration"),
                "shotBoundaries": [shot["startTime"] for shot in shots],
            },
            "camera": {
                "fov": 55,
                "shots": shots,
                "ease": shots[0]["ease"] if shots else "smoothstep",
            },
            "render": {
                "fps": fps,
                "resolution": resolution,
                "colorSpace": "srgb",
            },
            "output": {
                "framesDir": frames_dir,
                "framePrefix": "frame_",
                "framePadding": frame_padding,
                "videoPath": video_out,
            },
            "meta": {
                "notes": "Autogenerated by pipeline",
            },
        }
        config["timeline"]["totalFrames"] = int(duration * fps) + 1
        return config

    def _normalize_uri(self, uri: str) -> str:
        if uri.startswith("http"):
            return uri
        normalized = uri.replace("\\", "/")
        if not normalized.startswith("/"):
            normalized = f"/{normalized}"
        return normalized
